### ISSUE TITLE
Meta data is not being saved

### ISSUE THREAD

**Issue by BennieBe** [ballerburg9005/godot-metadata-inspector#1] opened 2020-06-07 15:33 UTC
Hi, 

I tried to use this plugin but everytime I save meta data of a node and restart godot, the meta information is gone ...

Also, how do I retrieve the meta data from the node in a script?
Might be good to add how to get and set metadata in the Readme...

**Comment by ballerburg9005** [comment] 2020-06-20 01:34
What version of Godot are you using? 

Are you using the recent version of Metadata Inspector?

If you give me your project and Godot binary I will check it out.

You can use set_meta() and get_meta() from Object, it is documented.

**Comment by BennieBe** [comment] 2020-06-21 12:57
Hi, I use Godot version 3.2.1, and the most recent Metadata Inspector version. I pick a node, add the information e.g. Level and then "Level one" as String I leave the tab, I move back, I can see my entry.  
I quit Godot and restart my project, the entry is gone...

**Comment by realkotob** [comment] 2020-06-21 18:10
@BennieBe It would be best if you could share a small example project that can reproduce this.

I had this issue you're having but only with inherited nodes such as fbx files for 3D models, and I fixed it by clicking "Clear inheritence" on the root node.

**Comment by ballerburg9005** [comment] 2020-06-22 01:46
Yeah, I don't see how this is possible at all with the most recent Metadata Inspector. In an earlier version (0.1), I had not yet implemented undo/redo so it could produce this behavior if you don't hit save before closing. Maybe try deleting the addons folder and reinstall Metadata Inspector from the AssetLib.

Otherwise just upload your project with Godot installation somewhere, then I can check it out.

@asheraryam : Interesting. I will put that on my todo list.

**Comment by BennieBe** [comment] 2020-06-25 11:27
@ballerburg9005 how do I share my project with you? Can I e-mail it to you?

**Comment by ballerburg9005** [comment] 2020-06-27 19:23
You can use this email: github@ballerburg9005.33mail.com

Or post it here.

**Comment by BennieBe** [comment] 2020-07-06 18:51
You can check out the project under this link: https://www.dropbox.com/s/pqwu5lftox70u8j/project.zip?dl=0

**Comment by ballerburg9005** [comment] 2020-07-06 20:08
Thanks. The issue seems to be only with nested scenes. 

The metadata of the sub-scene's instance is pulled once from the sub-scene on load of the parent scene and its never saved from the parent scene.

I will fix this by blocking edit from the parent scene.

You have to just edit the metadata inside the sub-scene and not from the parent scene for the sub-scene.

**Comment by ballerburg9005** [comment] 2020-07-06 22:37
It is fixed.

@asheraryam 

This should also fix the fbx issue you mentioned.

**Closed as completed by ballerburg9005** 2020-07-06 22:37 UTC
Labels: confirmed
